Repository CreaLink-SEPM/crealink, pull requests merged in 2023-12, with the labels that each got.

#6 # Front-end : create login page
  client/app/(authPage)/login/page.tsx
  client/app/(home)/layout.tsx
  client/app/(home)/page.tsx
  client/app/api/auth/[...nextauth]/options.ts
  client/app/api/auth/[...nextauth]/route.ts
  client/app/favicon.ico
  client/app/globals.css
  client/app/layout.tsx
  client/components.json
  client/components/common/ThemeToggleBtn.tsx
  client/components/theme-provider.tsx
  client/components/ui/alert-dialog.tsx
  client/components/ui/button.tsx
  client/components/ui/dropdown-menu.tsx
  client/components/ui/input.tsx
  client/components/ui/label.tsx
  client/components/ui/sheet.tsx
  client/lib/utils.ts
  client/package-lock.json
  client/package.json
  client/public/assets/icons/icon.svg
  client/public/assets/images/banner.svg
  client/src/_root/RootLayout.tsx
  client/src/lib/utils.ts
  client/tailwind.config.js
Labels: feature, Frontend

#8 #BE : Implement Post CRUD Operations
  README.md
  backend/.gitignore
  backend/app.js
  backend/components/configs/db.js
  backend/components/controllers/postController.js
  backend/components/controllers/userController.js
  backend/components/images/2023-11-30T10:50:16.030Z-best-hotel-bali.jpeg
  backend/components/images/2023-11-30T11:08:13.488Z-best-hotel-bali.jpeg
  backend/components/images/2023-12-02T03:53:20.503Z-best-hotel-bali.jpeg
  backend/components/images/2023-12-02T03:53:31.261Z-best-hotel-bali.jpeg
  backend/components/images/2023-12-02T04:00:40.089Z-au-lac-charner-hotel.jpg
  backend/components/middlewares/authMiddleware.js
  backend/components/models/postModel.js
  backend/components/models/userModel.js
  backend/components/routes/postRoutes.js
  backend/components/routes/router.js
  backend/components/routes/userRoutes.js
  backend/package-lock.json
  backend/package.json
Labels: feature

#11 #Fe : Write logic login and logout
  client/app/(authPage)/login/page.tsx
  client/app/(authPage)/register/page.tsx
  client/app/api/auth/signup/route.ts
  client/app/layout.tsx
  client/components/ui/toast.tsx
  client/components/ui/toaster.tsx
  client/components/ui/use-toast.ts
  client/package-lock.json
  client/package.json
  client/src/types/type.ts
  client/src/utils/auth.ts
Labels: feature

#15 #fix ant desgin
  client/app/(home)/layout.tsx
  client/app/(home)/page.tsx
  client/app/(search)/layout.tsx
  client/app/api/auth/[...nextauth]/options.ts
  client/app/api/auth/[...nextauth]/route.ts
  client/components/homepage/navbar.tsx
  client/lib/AntRegistry.tsx
  client/package-lock.json
  client/package.json
  client/src/app/(authPage)/layout.tsx
  client/src/app/(authPage)/login/page.tsx
  client/src/app/(authPage)/register/page.tsx
  client/src/app/(front)/layout.tsx
  client/src/app/(front)/loading.tsx
  client/src/app/(front)/page.tsx
  client/src/app/globals.css
  client/src/app/layout.tsx
  client/src/app/provider.tsx
  client/src/app/types/type.ts
  client/src/components/base/index.styled.tsx
  client/src/components/base/navbar.tsx
  client/src/components/common/ThemeToggleBtn.tsx
  client/src/components/common/loading.tsx
  client/src/components/theme-provider.tsx
  client/src/components/ui/alert-dialog.tsx
  client/src/components/ui/button.tsx
  client/src/components/ui/dropdown-menu.tsx
  client/src/components/ui/input.tsx
  client/src/components/ui/label.tsx
  client/src/components/ui/sheet.tsx
  client/src/components/ui/toast.tsx
  client/src/components/ui/toaster.tsx
  client/src/components/ui/use-toast.ts
  client/yarn.lock
Labels: Frontend

#19 # FE : create search page and setting function
  client/components/ui/alert-dialog.tsx
  client/components/ui/avatar.tsx
  client/components/ui/button.tsx
  client/components/ui/dialog.tsx
  client/components/ui/dropdown-menu.tsx
  client/package-lock.json
  client/package.json
  client/public/assets/icons/settings.png
  client/public/assets/icons/switch2side.png
  client/public/assets/images/avatar.png
  client/src/app/(front)/page.tsx
  client/src/app/layout.tsx
  client/src/components/base/BaseComponent.tsx
  client/src/components/base/LeftSideBar.tsx
  client/src/components/base/RightSideBar.tsx
  client/src/components/base/navbar.tsx
  client/src/components/common/AvatarSetting.tsx
  client/src/components/common/DropDownMenu.tsx
  client/src/components/common/SignOutBtn.tsx
  client/src/components/common/ThemeToggleBtn.tsx
  client/src/components/explore/SearchBar.tsx
  client/yarn.lock
Labels: Frontend

#20 create footer and edit user profile
  client/src/app/(front)/page.tsx
  client/src/app/layout.tsx
  client/src/components/common/AvatarSetting.tsx
  client/src/components/common/Footer.tsx
  client/src/components/explore/SearchBar.tsx
  client/src/components/user/EditProfile.tsx
Labels: feature, Frontend

#21 Add sending mail function
  server/components/middlewares/googleAuthenticator.js
Labels: feature

#22 Backend/posting api
  README.md
  backend/app.js
  backend/components/configs/db.js
  backend/components/controllers/postController.js
  backend/components/controllers/userController.js
  backend/components/images/2023-11-30T10:50:16.030Z-best-hotel-bali.jpeg
  backend/components/images/2023-11-30T11:08:13.488Z-best-hotel-bali.jpeg
  backend/components/images/2023-12-02T03:53:20.503Z-best-hotel-bali.jpeg
  backend/components/images/2023-12-02T03:53:31.261Z-best-hotel-bali.jpeg
  backend/components/images/2023-12-02T04:00:40.089Z-au-lac-charner-hotel.jpg
  backend/components/middlewares/authMiddleware.js
  backend/components/models/postModel.js
  backend/components/models/userModel.js
  backend/components/routes/postRoutes.js
  backend/components/routes/router.js
  backend/components/routes/userRoutes.js
  backend/package-lock.json
  backend/package.json
  server/.env-example
  server/app.js
  server/components/configs/db.js
  server/components/controllers/postController.js
  server/components/controllers/userController.js
  server/components/middlewares/authMiddleware.js
  server/components/middlewares/googleAuthenticator.js
  server/components/models/postModel.js
  server/components/models/userModel.js
  server/components/routes/googleAuthRoutes.js
  server/components/routes/postRoutes.js
  server/components/routes/router.js
  server/components/routes/userRoutes.js
  server/components/utils/awsS3Util.js
  server/package-lock.json
  server/package.json
  server/socket.js
Labels: enhancement, feature

#23 #FE : create user profile page
  client/components/ui/card.tsx
  client/components/ui/tabs.tsx
  client/package-lock.json
  client/package.json
  client/public/assets/images/profile.jpg
  client/src/app/(front)/page.tsx
  client/src/app/(front)/search/page.tsx
  client/src/components/base/navbar.tsx
  client/src/components/common/Footer.tsx
  client/src/components/common/ProfilePage.tsx
  client/src/components/common/loading.tsx
  client/yarn.lock
Labels: Frontend

#29 Finish comments and update admin feature
  server/.DS_Store
  server/app.js
  server/components/.DS_Store
  server/components/configs/db.js
  server/components/controllers/commentController.js
  server/components/controllers/postController.js
  server/components/controllers/userController.js
  server/components/images/.DS_Store
  server/components/images/2023-12-14T03:27:43.008Z-tiem-ca-phe-hoang-hon-chieu-1.jpg
  server/components/images/2023-12-14T03:37:16.771Z-tiem-cafe-hoang-hon-chieu-da-lat-ivivu-6.jpg
  server/components/images/2023-12-14T03:39:08.474Z-tiem-cafe-hoang-hon-chieu-da-lat-ivivu-6.jpg
  server/components/images/2023-12-14T03:39:09.647Z-tiem-cafe-hoang-hon-chieu-da-lat-ivivu-6.jpg
  server/components/middlewares/authMiddleware.js
  server/components/models/commentModel.js
  server/components/models/postModel.js
  server/components/models/userModel.js
  server/components/routes/adminRoutes.js
  server/components/routes/commentRoutes.js
  server/components/routes/router.js
  server/components/routes/userRoutes.js
Labels: enhancement, feature

#30 Fix postController
  server/components/controllers/postController.js
Labels: fixed

#31 Update admin feature
  .DS_Store
  server/api-document.md
  server/comment-api-documment.md
  server/components/controllers/adminController.js
  server/components/controllers/postController.js
  server/components/images/2023-12-18T14:18:11.510Z-tui-mo-to-2.jpg
  server/components/images/2023-12-18T14:23:33.981Z-tui-mo-to-2.jpg
  server/components/images/2023-12-18T14:23:37.711Z-tui-mo-to-2.jpg
  server/components/images/2023-12-18T14:40:22.700Z-tui-mo-to-2.jpg
  server/components/images/2023-12-18T14:40:26.227Z-tui-mo-to-2.jpg
  server/components/images/2023-12-18T14:40:39.483Z-tui-mo-to-2.jpg
  server/components/images/2023-12-18T14:42:58.185Z-tui-mo-to-2.jpg
  server/components/images/2023-12-18T14:46:40.211Z-tui-mo-to-2.jpg
  server/components/images/2023-12-18T14:48:58.021Z-tui-mo-to-2.jpg
  server/components/images/2023-12-18T14:49:52.058Z-tui-mo-to-2.jpg
  server/components/images/2023-12-18T14:49:57.188Z-tui-mo-to-2.jpg
  server/components/images/2023-12-18T14:53:31.635Z-tui-mo-to-2.jpg
  server/components/images/2023-12-18T14:57:31.752Z-tui-mo-to-2.jpg
  server/components/images/2023-12-21T12:17:53.100Z-thum-1200x676-25.jpg
  server/components/images/2023-12-21T12:24:39.048Z-thum-1200x676-25.jpg
  server/components/models/reportedPost.js
  server/components/routes/adminRoutes.js
  server/components/routes/postRoutes.js
  server/post-api-document.md
Labels: enhancement

#32 Backend/user api enhancement
  server/components/controllers/userController.js
  server/components/models/userModel.js
  server/components/routes/userRoutes.js
Labels: documentation, enhancement

#33 Be/interaction
  server/app.js
  server/components/controllers/userController.js
  server/components/images/2023-12-14T03:27:43.008Z-tiem-ca-phe-hoang-hon-chieu-1.jpg
  server/components/images/2023-12-14T03:37:16.771Z-tiem-cafe-hoang-hon-chieu-da-lat-ivivu-6.jpg
  server/components/images/2023-12-14T03:39:08.474Z-tiem-cafe-hoang-hon-chieu-da-lat-ivivu-6.jpg
  server/components/images/2023-12-14T03:39:09.647Z-tiem-cafe-hoang-hon-chieu-da-lat-ivivu-6.jpg
  server/components/images/2023-12-18T14:18:11.510Z-tui-mo-to-2.jpg
  server/components/images/2023-12-18T14:23:33.981Z-tui-mo-to-2.jpg
  server/components/images/2023-12-18T14:23:37.711Z-tui-mo-to-2.jpg
  server/components/images/2023-12-18T14:40:22.700Z-tui-mo-to-2.jpg
  server/components/images/2023-12-18T14:40:26.227Z-tui-mo-to-2.jpg
  server/components/images/2023-12-18T14:40:39.483Z-tui-mo-to-2.jpg
  server/components/images/2023-12-18T14:42:58.185Z-tui-mo-to-2.jpg
  server/components/images/2023-12-18T14:46:40.211Z-tui-mo-to-2.jpg
  server/components/images/2023-12-18T14:48:58.021Z-tui-mo-to-2.jpg
  server/components/images/2023-12-18T14:49:52.058Z-tui-mo-to-2.jpg
  server/components/images/2023-12-18T14:49:57.188Z-tui-mo-to-2.jpg
  server/components/images/2023-12-18T14:53:31.635Z-tui-mo-to-2.jpg
  server/components/images/2023-12-18T14:57:31.752Z-tui-mo-to-2.jpg
  server/components/images/2023-12-21T12:17:53.100Z-thum-1200x676-25.jpg
  server/components/images/2023-12-21T12:24:39.048Z-thum-1200x676-25.jpg
  server/components/images/2023-12-22T09:47:29.957Z-photo-1-156090803009454406232.webp
  server/components/images/2023-12-22T09:48:32.387Z-photo-1-156090803009454406232.webp
  server/components/images/2023-12-22T10:02:33.931Z-dia-diem-du-lich-da-lat-1_86dc1307188e41f284a1227679f089b4_grande.webp
  server/components/images/2023-12-22T10:20:15.284Z-dia-diem-du-lich-da-lat-1_86dc1307188e41f284a1227679f089b4_grande.webp
  server/components/models/userModel.js
  server/components/routes/userRoutes.js
Labels: documentation, enhancement, fixed

#34 Add git workflow yml file
  .github/workflows/ci-be.yaml
  .github/workflows/ci-fe.yml
Labels: enhancement

#35 Update and fix workflow
  .github/workflows/ci-be.yaml
Labels: fixed

#36 #Fe - create help center page
  client/components/ui/resizable.tsx
  client/components/ui/scroll-area.tsx
  client/components/ui/select.tsx
  client/package-lock.json
  client/package.json
  client/src/app/(front)/layout.tsx
  client/src/app/(front)/notifications/page.tsx
  client/src/app/(front)/search/page.tsx
  client/src/app/(helpCenter)/layout.tsx
  client/src/app/(helpCenter)/terms/page.tsx
  client/src/components/base/BaseComponent.tsx
  client/src/components/base/HelpCenterComponent.tsx
  client/src/components/base/LeftSideBar.tsx
  client/src/components/base/Navbar.tsx
  client/src/components/base/RightSideBar.tsx
  client/src/components/common/FavoritePage.tsx
  client/src/components/common/HelpCenterPage.tsx
  client/src/components/common/HomePage.tsx
  client/src/components/common/ProfilePage.tsx
  client/src/components/common/SidebarLinks.tsx
  client/src/components/explore/SearchBar.tsx
  client/yarn.lock
Labels: Frontend

#37 Add new root
  server/components/routes/router.js
Labels: fixed

#38 Update User API
  server/components/controllers/userController.js
Labels: documentation, enhancement

#39 Containerize backend API server
  server/.dockerignore
  server/Dockerfile
  server/components/controllers/commentController.js
  server/documents/api-document.md
  server/documents/comment-api-documment.md
  server/documents/post-api-document.md
  server/package.json
  server/source/app.js
  server/source/components/.DS_Store
  server/source/components/configs/db.js
  server/source/components/controllers/adminController.js
  server/source/components/controllers/commentController.js
  server/source/components/controllers/postController.js
  server/source/components/controllers/userController.js
  server/source/components/images/.DS_Store
  server/source/components/images/2023-12-22T09:47:29.957Z-photo-1-156090803009454406232.webp
  server/source/components/images/2023-12-22T09:48:32.387Z-photo-1-156090803009454406232.webp
  server/source/components/images/2023-12-22T10:02:33.931Z-dia-diem-du-lich-da-lat-1_86dc1307188e41f284a1227679f089b4_grande.webp
  server/source/components/images/2023-12-22T10:20:15.284Z-dia-diem-du-lich-da-lat-1_86dc1307188e41f284a1227679f089b4_grande.webp
  server/source/components/middlewares/authMiddleware.js
  server/source/components/middlewares/googleAuthenticator.js
  server/source/components/models/commentModel.js
  server/source/components/models/postModel.js
  server/source/components/models/reportedPost.js
  server/source/components/models/userModel.js
  server/source/components/routes/adminRoutes.js
  server/source/components/routes/commentRoutes.js
  server/source/components/routes/googleAuthRoutes.js
  server/source/components/routes/postRoutes.js
  server/source/components/routes/router.js
  server/source/components/routes/userRoutes.js
  server/source/components/utils/awsS3Util.js
  server/source/socket.js
Labels: enhancement

#41 Fix the user name searching query
  server/docker-setup.sh
  server/documents/api-document.md
  server/documents/comment-api-documment.md
  server/documents/post-api-document.md
  server/documents/user-api-document.md
  server/source/components/controllers/userController.js
  server/source/components/models/commentModel.js
  server/source/components/routes/commentRoutes.js
  server/source/components/routes/postRoutes.js
  server/source/components/routes/userRoutes.js
Labels: enhancement, fixed

#44 Update homepage api
  server/admin-api-document.md
  server/comment-api-documment.md
  server/package-lock.json
  server/package.json
  server/post-api-document.md
  server/source/app.js
  server/source/components/configs/openai.js
  server/source/components/controllers/commentController.js
  server/source/components/controllers/postController.js
  server/source/components/controllers/userController.js
  server/source/components/routes/router.js
Labels: documentation, enhancement, feature, fixed

#47 Add more attributes response
  server/source/components/controllers/userController.js
  server/source/components/images/.DS_Store
  server/source/components/images/2023-12-22T09:47:29.957Z-photo-1-156090803009454406232.webp
  server/source/components/images/2023-12-22T09:48:32.387Z-photo-1-156090803009454406232.webp
  server/source/components/images/2023-12-22T10:02:33.931Z-dia-diem-du-lich-da-lat-1_86dc1307188e41f284a1227679f089b4_grande.webp
  server/source/components/images/2023-12-22T10:20:15.284Z-dia-diem-du-lich-da-lat-1_86dc1307188e41f284a1227679f089b4_grande.webp
Labels: enhancement

#48 Change API response structure & Mute AI function
  server/source/components/controllers/postController.js
  server/source/components/controllers/userController.js
Labels: enhancement
