Repository CreaLink-SEPM/crealink, pull requests merged in 2024-01, with the labels that each got.

#52 Remove testing components
  server/source/com/.DS_Store
  server/source/com/configs/db.js
  server/source/com/configs/openai.js
  server/source/com/controllers/adminController.js
  server/source/com/controllers/commentController.js
  server/source/com/controllers/notificationController.js
  server/source/com/controllers/postController.js
  server/source/com/controllers/userController.js
  server/source/com/middlewares/authMiddleware.js
  server/source/com/middlewares/googleAuthenticator.js
  server/source/com/models/commentModel.js
  server/source/com/models/postModel.js
  server/source/com/models/reportedPost.js
  server/source/com/models/userModel.js
  server/source/com/routes/adminRoutes.js
  server/source/com/routes/commentRoutes.js
  server/source/com/routes/googleAuthRoutes.js
  server/source/com/routes/notificationRoutes.js
  server/source/com/routes/postRoutes.js
  server/source/com/routes/router.js
  server/source/com/routes/userRoutes.js
  server/source/com/utils/awsS3Util.js
Labels: fixed

#53 Integrate OpenAI
  server/source/components/controllers/postController.js
  server/source/components/routes/postRoutes.js
Labels: enhancement

#54 Update post api document and post controller
  server/documents/post-api-document.md
  server/source/components/controllers/postController.js
  server/source/components/routes/postRoutes.js
Labels: documentation, enhancement

#55 Be/test api
  server/source/components/controllers/userController.js
  server/source/components/routes/commentRoutes.js
  server/source/components/routes/postRoutes.js
  server/source/index.html
  server/source/javascript.js
  server/source/socket.js
  server/source/test/socketClient.js
Labels: enhancement, fixed

#58 New updates
  server/source/components/controllers/userController.js
  server/source/components/models/userModel.js
Labels: enhancement

#57 Update comment api document and fix upload image error
  server/documents/comment-api-documment.md
  server/documents/post-api-document.md
  server/documents/user-api-document.md
  server/source/ai.html
  server/source/app.js
  server/source/components/controllers/commentController.js
  server/source/components/controllers/postController.js
  server/source/components/images/2024-01-08T03:42:35.666Z-photo-1-156090803009454406232.webp
  server/source/components/images/2024-01-08T03:56:28.895Z-photo-1-156090803009454406232.webp
  server/source/components/routes/commentRoutes.js
  server/source/components/routes/postRoutes.js
Labels: documentation, enhancement

#59 finish logic for user profile
  client/components/ui/sheet.tsx
  client/lib/serverMethod.ts
  client/next.config.js
  client/src/app/(front)/profile/page.tsx
  client/src/app/(front)/search/page.tsx
  client/src/app/(front)/user/[id]/page.tsx
  client/src/app/api/auth/[...nextauth]/options.ts
  client/src/app/api/users/[id]/route.ts
  client/src/app/api/users/followers/route.ts
  client/src/app/api/users/posts/route.ts
  client/src/app/api/users/route.ts
  client/src/components/base/LeftSideBar.tsx
  client/src/components/common/AvatarSetting.tsx
  client/src/components/explore/SearchBar.tsx
  client/src/components/user/EditProfile.tsx
  client/src/components/user/Support.tsx
  client/src/types/type.ts
Labels: feature

#61 Be/test api
  git_push.sh
  server/source/components/controllers/userController.js
  server/source/components/models/userModel.js
Labels: enhancement

#62 New changes added
  server/source/components/controllers/userController.js
Labels: enhancement

#63 New changes added
  server/source/components/controllers/userController.js
Labels: enhancement

#64 New changes added
  server/source/components/controllers/userController.js
Labels: enhancement

#65 New changes added
  server/source/components/controllers/userController.js
Labels: enhancement

#66 New changes added
  server/source/components/controllers/userController.js
  server/source/components/routes/userRoutes.js
Labels: fixed

#67 New changes added
  server/source/components/controllers/userController.js
Labels: enhancement, fixed

#68 Be/test api
  server/source/components/controllers/userController.js
Labels: enhancement, fixed

#70 New changes added
  server/source/components/controllers/userController.js
Labels: fixed

#69 Fix toggle like and saved posts
  client/package-lock.json
  client/package.json
  client/src/app/api/auth/[...nextauth]/options.ts
  client/src/components/common/Post.tsx
  client/yarn.lock
  server/source/components/controllers/postController.js
  server/source/components/images/2024-01-09T06:38:43.560Z-1000_F_213200366_CEHLufIVW8hMjngNUfkRjxZpeiCzkB5m.jpg
Labels: enhancement, fixed

#73 New changes added
  server/source/components/controllers/userController.js
  server/source/components/models/userModel.js
Labels: enhancement

#74 Be/notification feat
  server/git_pull.sh
  server/source/components/controllers/postController.js
  server/source/components/controllers/userController.js
  server/source/components/models/userModel.js
Labels: enhancement

#75 New changes added
  server/documents/user-api-document.md
  server/source/components/controllers/userController.js
Labels: documentation, enhancement

#72 Remove authorization middleware for GET methods
  client/src/components/common/Post.tsx
  server/source/components/routes/commentRoutes.js
  server/source/components/routes/postRoutes.js
Labels: fixed

#77 be/noti-update
  server/source/components/controllers/userController.js
  server/source/components/models/userModel.js
  server/source/components/routes/userRoutes.js
Labels: enhancement

#82 fix report button and share link event button
  client/src/components/common/Post.tsx
Labels: feature

#83 Be/notification update
  server/source/components/controllers/notificationController.js
  server/source/components/controllers/postController.js
  server/source/components/controllers/userController.js
  server/source/components/models/userModel.js
Labels: enhancement
